image:
  name: cirrusci/flutter

stages:
- coverage
- release
- deploy

.add_api_key: &add_api_key |-
  LASTHASH=$(git rev-parse HEAD)
  printf "abstract class InstancesApiToken {\n  static const String token = '$INSTANCES_API_KEY';\n}" > lib/config/instances_api_token.dart

code_analyze:
  stage: coverage
  script:
    - flutter format lib/ test/ --set-exit-if-changed
    - flutter analyze

test:
  stage: coverage
  script: [flutter test]

build_web:
  stage: coverage
  before_script: [*add_api_key]
  script:
    - flutter pub get
    - flutter build web --release --verbose
  artifacts:
    paths:
      - build/web/

build_android_apk_debug:
  stage: coverage
  before_script:
    - *add_api_key
    - ./scripts/prepare-android-release.sh
  script:
    - flutter pub get
    - flutter build apk
  artifacts:
    when: on_success
    paths:
      - build/app/outputs/apk/debug/app-release.apk
  except:
    - main
    - tags

build_android_apk:
  stage: coverage
  before_script:
    - *add_api_key
    - ./scripts/prepare-android-release.sh
  script:
    - flutter pub get
    - flutter build apk --release
  artifacts:
    when: on_success
    paths:
      - build/app/outputs/apk/release/app-release.apk
  only:
    - main
    - tags

pages:
  stage: deploy
  image: ruby:latest
  script:
    - mv build/web/ public/
  artifacts:
    paths:
      - public
  only:
    - main
