name: fluffypix
description: A new Flutter project.
publish_to: 'none'
version: 0.2.0+0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.0
  intl: ^0.17.0
  http: ^0.13.3
  cached_network_image: ^3.1.0
  hive_flutter: ^1.1.0
  url_launcher: ^6.0.9
  flutter_matrix_html: ^1.1.0
  flutter_inappwebview: ^5.7.1
  flutter_app_badger: ^1.3.0
  uni_links: ^0.5.1
  adaptive_dialog: ^1.1.0
  pull_to_refresh: ^2.0.0
  badges: ^2.0.1
  image_picker: ^0.8.3
  share: ^2.0.4
  flutter_blurhash: ^0.7.0
  receive_sharing_intent: ^1.4.5
  package_info: ^2.0.2
  elliptic: ^0.3.5
  firebase_messaging: ^14.1.0
  flick_video_player: ^0.5.0
  video_player: ^2.1.15
  flutter_local_notifications: ^9.1.4
  shared_preferences: ^2.0.15
  dynamic_color: ^1.4.0

dev_dependencies:
  flutter_lints: ^2.0.1
  import_sorter: ^4.6.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/

dependency_overrides:
  provider: 6.0.0