name: fluffypix
description: A new Flutter project.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^5.0.0
  intl: ^0.17.0
  http: ^0.13.3
  cached_network_image: ^3.0.0
  hive_flutter: ^1.1.0
  url_launcher: ^6.0.9
  simple_html_css: ^3.0.1
  flutter_inappwebview: ^5.3.2
  uni_links: ^0.5.1
  adaptive_dialog: ^1.1.0
  pull_to_refresh: ^2.0.0
  badges: ^2.0.1
  image_picker: ^0.8.3
  share: ^2.0.4
  flutter_blurhash: ^0.6.0
  receive_sharing_intent: ^1.4.5
  package_info: ^2.0.2
  webcrypto: ^0.5.2
  firebase_messaging: ^10.0.6

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/